version: '3.9'
services:
  azure.storage.emulator:
    image: "mcr.microsoft.com/azure-storage/azurite:latest"        
    container_name: azure.storage.emulator
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
  mssql:
    build: ./db
    ports:
      - "1433:1433"
